ssh_config: .teefaa/ssh-config

host_config:
  hostname: centos65
  power_driver: virtualbox
  power_driver_config:
    # check the vbox name with "VBoxManage list vms"
    vbox_name: teefaa_centos65_1389712867983_14657
  boot_driver: virtualbox
  boot_driver_config:
    diskless_boot: iso
    iso_file: .teefaa/teefaa-debian-live.iso

# Baremetal
#dest_host:
#  hostname: host1
#  power_driver: ipmi
#  power_driver_config:
#    ipmi_password: XXXXXXXXXX
#    ipmi_user: ipmiadmin
#    bmc_address: 192.168.1.1
#  boot_driver: pxe
#  boot_driver_config:
#    boot_config_file: /tftpboot/pxelinux.cfg/host1
#    diskless_boot_config_file: /tftpboot/pxelinux.cfg/netboot
#    disk_boot_config_file: /tftpboot/pxelinux.cfg/localboot

disk_config:
  label_type: mbr
  device: /dev/sda
  swap:
    size: 2
  system:
    size: 10
    format: ext4
  data:
    size: -1
    dir: /data
    format: xfs

network_config:
  add:
    eth0:
      bootp: dhcp
    #eth1:
    #  bootp: static
    #  address: 192.168.32.101
    #  netmask: 255.255.255.0
    #  gateway: 192.168.32.254
    #dnsserver:
    #  address: 192.168.32.1
    #  interface: eth1
  #delete:
    #- ib0
    #- br0
