ssh_config: .teefaa/ssh-config

snapshot_config:
  snapshot_path: .teefaa/ubuntu1204-2014-01-12.squashfs
  hostname: ubuntu1204
  os:
    distro: ubuntu
    ver: 12.04
  exclude:
    - /path/to/excluded/dir

#iso_config:
#  base_iso: debian-live-7.2-amd64-standard.iso
#  base_iso_url: http://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-7.2-amd64-standard.iso
#  builder:
#    hostname: hostname
#    distro: ubuntu
#  iso_path: .teefaa/teefaa-debian-live.iso

disk_config:
  label_type: mbr
  device: /dev/sda
  swap:
    size: 2
  system:
    size: 10
    format: ext4
  data:
    size: -1
    dir: /data
    format: xfs

bootloader_config:
  type: grub2
